source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '14.1'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'iosApp' do
  pod 'MultiPlatformLibrary', :path => '../MultiPlatformLibrary'
end
